runtime: java21
entrypoint: 'java -jar server-all.jar'
env_variables:
  JDBC_URL: secret:jdbc-url
handlers:
  - url: /api/.*
    script: auto

  - url: /static
    static_dir: webclient/static

  - url: /(.*\.(json|ico|js))$
    static_files: webclient/\1
    upload: webclient/.*\.(json|ico|js)$

  - url: /.*
    static_files: webclient/index.html
    upload: webclient/index.html